--1. Create a SELECT statement which joins ptbl_Transaction with ptbl_Product to ptbl_Subcategory.

SELECT SUBCATEGORY_NAME,TRANSACTION_DATE, SUM(Actual_Cost) Total_Actual_Cost, SUM(Quantity) Total_Quantity
FROM PTBL_TRANSACTION
NATURAL LEFT JOIN PTBL_PRODUCT 
--USING(PRODUCT_ID)
NATURAL LEFT JOIN PTBL_SUBCATEGORY 
--USING(PRODUCT_SUBCATEGORY_ID)
GROUP BY SUBCATEGORY_NAME,TRANSACTION_DATE
ORDER BY SUBCATEGORY_NAME,TRANSACTION_DATE;

--2. Create a SELECT statement which counts the number of PRODUCT_ID in ptbl_Product for each Subcategory_Name in ptbl_Subcategory and for each Category_Name in ptbl_Category.
SELECT SUBCATEGORY_NAME,CATEGORY_NAME, COUNT(PRODUCT_ID) AS Product_Number
FROM PTBL_SUBCATEGORY
NATURAL LEFT JOIN PTBL_PRODUCT
NATURAL LEFT JOIN PTBL_CATEGORY
GROUP BY SUBCATEGORY_NAME,CATEGORY_NAME
ORDER BY SUBCATEGORY_NAME,CATEGORY_NAME;