--1. Create a SELECT statement which joins ptbl_Transaction with ptbl_Product (they join together using Product_ID).

SELECT PRODUCT_NAME, SUM(Actual_Cost) Total_Actual_Cost, SUM(Quantity) Total_Quantity
FROM PTBL_TRANSACTION
NATURAL JOIN PTBL_PRODUCT
--USING(PRODUCT_ID)
--ON (PTBL_PRODUCT.PRODUCT_ID=PTBL_TRANSACTION.PRODUCT_ID)
GROUP BY PRODUCT_NAME
ORDER BY PRODUCT_NAME;

--2. Create a SELECT statement which joins together ptbl_Subcategory and ptbl_Category, and returns the Category_Name and the Subcategory_Name.
SELECT CATEGORY_NAME, SUBCATEGORY_NAME
FROM PTBL_SUBCATEGORY
NATURAL JOIN PTBL_CATEGORY
--USING(PRODUCT_CATEGORY_ID)
ORDER BY CATEGORY_NAME;

SELECT  CATEGORY_NAME, COUNT(PTBL_SUBCATEGORY.PRODUCT_SUBCATEGORY_ID) NOMBRE_SUBCAT
FROM PTBL_SUBCATEGORY
RIGHT JOIN PTBL_CATEGORY
USING(PRODUCT_CATEGORY_ID)
GROUP BY (CATEGORY_NAME);


--3. Create a SELECT statement which counts the number of PRODUCT_ID in ptbl_Product for each Subcategory_Name in ptbl_Subcategory.
SELECT SUBCATEGORY_NAME , COUNT(PTBL_PRODUCT.PRODUCT_ID) NOMBRE_SUBCAT
FROM PTBL_PRODUCT
NATURAL JOIN PTBL_SUBCATEGORY
--USING(PRODUCT_SUBCATEGORY_ID)
GROUP BY (SUBCATEGORY_NAME)
ORDER BY SUBCATEGORY_NAME;

SELECT  PRODUCT_SUBCATEGORY_ID,  COUNT(PTBL_PRODUCT.PRODUCT_ID) NOMBRE_SUBCAT
FROM PTBL_PRODUCT 
GROUP BY (PRODUCT_SUBCATEGORY_ID)
ORDER BY PRODUCT_SUBCATEGORY_ID;