/*DROP TABLE TBL_TRANSACTION;
CREATE TABLE TBL_TRANSACTION(
AMOUNT NUMBER (15,2) NOT NULL,
DATE_OF_TRANSACTION DATE NOT NULL,
EMPLOYEE_NUMBER NUMBER(4,0) NOT NULL
)*/

SELECT * 
FROM TBL_TRANSACTION
NATURAL LEFT JOIN TBL_EMPLOYEE