CREATE TABLE TBL_DEPARTMENT
(DEPARTMENT VARCHAR2(20 CHAR) NOT NULL,
 DEPARTMENT_HEAD VARCHAR2(20 CHAR) NOT NULL);
TRUNCATE TABLE TBL_DEPARTMENT;
COMMIT;
INSERT INTO TBL_DEPARTMENT VALUES('Customer Relations','Andrew');
INSERT INTO TBL_DEPARTMENT VALUES('Commercial','Bryan');
INSERT INTO TBL_DEPARTMENT VALUES('HR','Catherine');
INSERT INTO TBL_DEPARTMENT VALUES('Litigation','Andrew');
INSERT INTO TBL_DEPARTMENT VALUES('Accounts','James');
COMMIT;