INSERT INTO ptbl_Subcategory VALUES (1, 1, 'Mountain Bikes');
INSERT INTO ptbl_Subcategory VALUES (2, 1, 'Road Bikes');
INSERT INTO ptbl_Subcategory VALUES (3, 1, 'Touring Bikes');
INSERT INTO ptbl_Subcategory VALUES (4, 2, 'Handlebars');
INSERT INTO ptbl_Subcategory VALUES (5, 2, 'Bottom Brackets');
INSERT INTO ptbl_Subcategory VALUES (6, 2, 'Brakes');
INSERT INTO ptbl_Subcategory VALUES (7, 2, 'Chains');
INSERT INTO ptbl_Subcategory VALUES (8, 2, 'Cranksets');
INSERT INTO ptbl_Subcategory VALUES (9, 2, 'Derailleurs');
INSERT INTO ptbl_Subcategory VALUES (10, 2, 'Forks');
INSERT INTO ptbl_Subcategory VALUES (11, 2, 'Headsets');
INSERT INTO ptbl_Subcategory VALUES (12, 2, 'Mountain Frames');
INSERT INTO ptbl_Subcategory VALUES (13, 2, 'Pedals');
INSERT INTO ptbl_Subcategory VALUES (14, 2, 'Road Frames');
INSERT INTO ptbl_Subcategory VALUES (15, 2, 'Saddles');
INSERT INTO ptbl_Subcategory VALUES (16, 2, 'Touring Frames');
INSERT INTO ptbl_Subcategory VALUES (17, 2, 'Wheels');
INSERT INTO ptbl_Subcategory VALUES (18, 3, 'Bib-Shorts');
INSERT INTO ptbl_Subcategory VALUES (19, 3, 'Caps');
INSERT INTO ptbl_Subcategory VALUES (20, 3, 'Gloves');
INSERT INTO ptbl_Subcategory VALUES (21, 3, 'Jerseys');
INSERT INTO ptbl_Subcategory VALUES (22, 3, 'Shorts');
INSERT INTO ptbl_Subcategory VALUES (23, 3, 'Socks');
INSERT INTO ptbl_Subcategory VALUES (24, 3, 'Tights');
INSERT INTO ptbl_Subcategory VALUES (25, 3, 'Vests');
INSERT INTO ptbl_Subcategory VALUES (26, 4, 'Bike Racks');
INSERT INTO ptbl_Subcategory VALUES (27, 4, 'Bike Stands');
INSERT INTO ptbl_Subcategory VALUES (28, 4, 'Bottles and Cages');
INSERT INTO ptbl_Subcategory VALUES (29, 4, 'Cleaners');
INSERT INTO ptbl_Subcategory VALUES (30, 4, 'Fenders');
INSERT INTO ptbl_Subcategory VALUES (31, 4, 'Helmets');
INSERT INTO ptbl_Subcategory VALUES (32, 4, 'Hydration Packs');
INSERT INTO ptbl_Subcategory VALUES (33, 4, 'Lights');
INSERT INTO ptbl_Subcategory VALUES (34, 4, 'Locks');
INSERT INTO ptbl_Subcategory VALUES (35, 4, 'Panniers');
INSERT INTO ptbl_Subcategory VALUES (36, 4, 'Pumps');
INSERT INTO ptbl_Subcategory VALUES (37, 4, 'Tires and Tubes');
COMMIT;