SELECT COUNT(*) FROM PTBL_TRANSACTION;

TRUNCATE TABLE ptbl_Product;

SELECT COUNT(*) FROM ptbl_Product;

DESCRIBE  PTBL_SUBCATEGORY

DROP TABLE  PTBL_SUBCATEGORY;

SELECT COUNT(*) FROM PTBL_SUBCATEGORY;
DROP TABLE  PTBL_TRANSACTION;
DROP TABLE  ptbl_Product;
DROP TABLE  PTBL_SUBCATEGORY;
DROP TABLE  ptbl_Category;


SELECT *
FROM ptbl_subcategory;

SELECT * 
FROM ptbl_subcategory
WHERE trim(lower(Subcategory_Name)) LIKE '%bike%';


SELECT * 
FROM ptbl_subcategory
WHERE PRODUCT_CATEGORY_ID <>2;

SELECT * 
FROM ptbl_subcategory
WHERE PRODUCT_CATEGORY_ID <=2;


SELECT * 
FROM ptbl_subcategory
WHERE PRODUCT_CATEGORY_ID BETWEEN 3 and 5;